### PR TITLE
Update .gitattributes to exclude more useless files

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @pkopac @sbrych

I found more entries which could be added to the .gitattributes files
This is similar to https://github.com/chartmogul/chartmogul-php/pull/103

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Friendly ping @pkopac @sbrych

**Comment by sbrych** [comment]
> Friendly ping @pkopac @sbrych

Hey @VincentLanglet, apologies for the late response, life got in the way :)
Thank you for the PR, We'll merge it as soon as we're done with some underlying issues (failing test suite for example)

**Comment by VincentLanglet** [comment]
> > Friendly ping @pkopac @sbrych
> 
> Hey @VincentLanglet, apologies for the late response, life got in the way :) Thank you for the PR, We'll merge it as soon as we're done with some underlying issues (failing test suite for example)

Hi, I rebased and there are less (unrelated) failure but still some.
Should I do something ? Thanks :)

**Comment by VincentLanglet** [comment]
I fixed the ci @sbrych @pkopac

**Review by sbrych — APPROVED** [review]

**Comment by sbrych** [comment]
Thank you @VincentLanglet, merging now

**Pull request merged**
