### PR TITLE
chore: PHP8 suppport

### PR DESCRIPTION
**Pull request by countless-integers**
* chore: add new matrix row on travis
* chore: build another container version for php8 with xdebug3

### CODE REVIEW

**Comment by countless-integers** [comment]
I'm a bit confused about how you guys do testing. Doesn't seem to run for PR, is that intentional?

e.g. it looks like [this change](https://github.com/chartmogul/chartmogul-php/commit/266357f42371e18f81901dab5f15cf13d2eec6b6) is breaking one of the unit tests. Also coding style tool reports an issue with one of the file containing 2 classes. Yet main branch is listed as passing all checks... What am I missing here?

**Comment by pkopac** [comment]
@countless-integers recent changes have been made without fixing the fact that https://travis-ci.org/ doesn't run anymore. We need to add configuration for GitHub Actions. Thanks for the contribution, we'll check it out once the build is working.

**Comment by countless-integers** [comment]
Ah yes, had to do the same for one of my packages yesterday.

**Comment by AidasK** [comment]
@hassansin would love to see this merged

**Review by hassansin — APPROVED** [review]

**Comment by countless-integers** [comment]
I've merged `main`, but the workflow seems to have an issue with fetching the code from my fork + static analysis errors that look like they're not directly related to this branch. Any idea how to solve this?

**Comment by hassansin** [comment]
We've fixed the static analysis issues in the main branch. Fetching code from forked repository doesn't seem to work, but it's not block us from merging the PR. One minor issue - ,when testing locally with php8,  it fails to run code coverage. I think we need to upgrade to phpunit 9. Anyway I'll merge the PR. Thanks a lot for your effort 👍

**Pull request merged**
