### PR TITLE
use psr client interface instead of php-http client interface

### PR DESCRIPTION
**Pull request by slepic**
Heya

the chartmogul client class does not really need php-http `HttpClient` which is itself documented with recommendation to typehint agains PSR ClientInterface.

So, this PR makes that change. Unfortunately it brings another BC break because it eases the typehint in ClientInterface::getHttpClient and setHttpClient methods. But hopefully this shouldn't be a problem because noone is likely to reimplement that interface.

---
Further I would like to get rid of the auto discovery because actually nothing from php-http is necesary for this lib. I want to be able to inject psr client without need to install any of the php-http stuff... But this should probably go to its own issue...

### CODE REVIEW

**Comment by hassansin** [comment]
@slepic  build is failing because of a missing package required by `psr/http-client-implementation`. We use [mock-client](https://packagist.org/packages/php-http/mock-client)` which doesn't provide this virtual package. Need to use alternative mocking package.

**Comment by slepic** [comment]
@hassansin hi, sorry for no response for so long, i've been rather busy.... There should be nothing preventing mock-client from providing the virtual package, I have raised an issue there. If it passes, it should be matter of simply updating the mock-client lib when it's released...

**Comment by hassansin** [comment]
@slepic can you please sync your branch with upstream? We've pushed some fixes so tests don't fail on PRs from forked repositories.

**Comment by slepic** [comment]
@hassansin done

**Review by hassansin — APPROVED** [review]

**Pull request merged**
